/**
 * Created with JetBrains PhpStorm.
 * Author: Kirill Cherkashin
 *
 */

"use strict";

Ext.define( 'chords.store.songs', {
    extend: 'Ext.data.Store',
    shuffledItems: null,
    /**
     * This function creates and shuffles an array with the same amount of items, the store has.
     * The program can pop random items, and they won't repeat.
     */
    shuffle: function () {

        var i;
        var max = this.getCount();
        this.shuffledItems = [];
        for( i = 0; i < max; i++ ) {
            this.shuffledItems.push( i );
        }

        //Shuffles an array using fisher-yates method.
        for( i = this.shuffledItems.length - 1; i > 0; i-- ) {
            var j = Math.floor( Math.random() * (i + 1) );
            var temp = this.shuffledItems[i];
            this.shuffledItems[i] = this.shuffledItems[j];
            this.shuffledItems[j] = temp;
        }
    },
    /**
     * Pulls random item.
     *
     */
    getRandomItem: function () {
        if( this.shuffledItems === null ) {
            this.shuffle();
        }
        return this.getAt( this.shuffledItems.pop() );

    },

    config: {
        model: 'chords.model.song',
        proxy: {
            type: "ajax",
            /**
             * This file is automatically generated every time the git repository is updated.
             */
            url: "songs/songs.json",
            reader: {
                type: "json"
            }
        },
        autoLoad: true
    }

} );